# Generated by Django 4.2.1 on 2023-06-05 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='age',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='group',
            name='capacity',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='instructor',
            name='specialization',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
