# Generated by Django 4.2.1 on 2023-06-06 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_club', '0003_group_client_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='client_name',
        ),
        migrations.AddField(
            model_name='group',
            name='client_name',
            field=models.ManyToManyField(to='fitness_club.client'),
        ),
    ]
