# Generated by Django 4.2.1 on 2023-06-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_club', '0004_remove_group_client_name_group_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='photo',
            field=models.ImageField(default='', upload_to='photo/%Y/%n/%d/'),
        ),
    ]
