# Generated by Django 4.2.1 on 2023-06-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_club', '0006_membership_remove_instructor_photo_alter_client_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='photo',
            field=models.ImageField(default='', upload_to='photos/%Y/%m/%d'),
        ),
    ]
