# Generated by Django 4.2.1 on 2023-06-07 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_club', '0002_alter_client_age'),
        ('fitness_club', '0007_instructor_photo'),
    ]

    operations = [
    ]
