# Generated by Django 4.2.1 on 2023-06-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_club', '0008_merge_0002_alter_client_age_0007_instructor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
