# Generated by Django 4.2.1 on 2023-06-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_club', '0009_membership_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='count',
            field=models.PositiveIntegerField(),
        ),
    ]
