# Generated by Django 4.2.1 on 2023-06-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_club', '0010_alter_membership_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='count',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
